sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_be4c395cafea_key -iv $encrypted_be4c395cafea_iv
  -in client-secret.json.enc -out client-secret.json -d
install: sudo ./setup_tests.sh && export PATH="${HOME}/google-cloud-sdk/bin:${PATH}"
after_success:
- mvn clean appengine:deploy
