sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_be4c395cafea_key -iv $encrypted_be4c395cafea_iv -in komeiji-bot-8d876f3ea563.json.enc -out komeiji-bot-8d876f3ea563.json -d && export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/komeiji-bot-8d876f3ea563.json"
  - export GOOGLE_CLOUD_PROJECT=api-project-93144643231
install: sudo ./setup_tests.sh && export PATH="${HOME}/google-cloud-sdk/bin:${PATH}"
after_success:
  - mvn clean appengine:deploy
